branches:
  only:
  - master
sudo: required
services:
- docker
language: node_js
node_js:
- 6
before_install:
  #Set up Docker exports
  - export AUTHOR=`git --no-pager show -s --format='%an <%ae>'`
  - export DATE=`TZ=America/New_York date "+%m-%d-%y-%H%M"`
  - export DOCKER_IMAGE="ctrp/nci-match-admin-tool-ui"
  - echo "TravisBuild=$TRAVIS_BUILD_NUMBER" > build_number.html &&
        echo "Commit=$TRAVIS_COMMIT" >> build_number.html       &&
        echo "TravisBuildID=$TRAVIS_BUILD_ID" >> build_number.html    &&
        echo "Author=$AUTHOR" >> build_number.html              &&
        echo "BuildTime=$DATE" >> build_number.html             &&
        echo "Docker=$DOCKER_IMAGE:$DATE" >> build_number.html
  - cat ./build_number.html
before_script:
  - cd common && npm install
  - cd ../search && npm install
  - cd common && npm install
  - ls -alth
  - cd ../api && npm install
  - cd ../client && npm install
  - cd ../index && npm install
  - pwd
  - ls -lah
script:
  - cd ../api && npm test
  # - pwd
  # - find ./
  # - istanbul cover test.js
  #Build Docker image
  - echo "DOCKER_USERNAME= $DOCKER_USERNAME"
  - docker build -t $DOCKER_IMAGE:$DATE -t $DOCKER_IMAGE:latest .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
after_success:
  - ls -alth
  # - codeclimate-test-reporter < lcov.info
  - docker images
  - docker push $DOCKER_IMAGE # Pushes both date and latest
  #Deploy to AWS IntTest
#  - docker run -it --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
#    -e AWS_DEFAULT_REGION=us-east-1 silintl/ecs-deploy
#    --cluster CTRP-IntTest-Backend --service-name CTRP-clinical-trials-api-INTTEST
#    -i $DOCKER_IMAGE:$DATE
 
  #Trigger Travis bdd tests
  # - curl -s -X POST -H "Content-Type:application/json" -H "Accept:application/json" 
  #   -H "Travis-API-Version:3" -H "Authorization:token $TRAVIS_TOKEN" 
  #   -d "{\"request\":{\"message\":\"Triggered by nci-match-patient-api $TRAVIS_COMMIT\", \"branch\":\"master\", \"config\":{\"env\":{\"matrix\":[\"TRIGGER_REPO=nci-match-patient-api;TRIGGER_VER=$DATE;CUC_TAG=@patients;AUTHOR=$AUTHOR\"]}}}}" 
  #   https://api.travis-ci.org/repo/CBIIT%2Fnci-uMatch-bddtests/requestsafter_script:
# - codeclimate-test-reporter < test/coverage/report-lcov/lcov.info
notifications:
  slack: clinicalbiomed:W5L3wQ69vtL1XJCo8uT3oQgY
#  addons:
#  code_climate:
#   repo_token: a3fe31ee4a1f9650502dea77ec832d8e953fae8e458c8e353c21cfff5af93490
